### ISSUE TITLE
Is it possible to ignore values when comparing

### ISSUE THREAD

**Issue by randy-girard** [Blargel/easy_diff#13]
Say I have the following:

```
a = { :a => 1 }
b = { :a => 2, :b => 5 }
remove, added = a.easy_diff(b) # => [{:a=>1}, {:b=>5, :a=>2}]
```

I would like to get a diff of only when the keys are added or removed, not if the value of a key changes like so:

```
a = { :a => 1 }
b = { :a => 2, :b => 5 }
remove, added = a.easy_diff(b, :ignore_values => true) # => [{}, {:b=>5}]
```

Is that possible?

**Comment by Blargel** [comment]
There's nothing like that for this gem and it doesn't seem like something I'd consider within the scope of what I intended for this gem. If you don't need to compare nested hashes, you could always just call the keys method on both hashes and compare the arrays to see which keys were added and removed. If you do need to compare nested hashes, then you're outta luck here. Sorry.

**Comment by randy-girard** [comment]
Ok thanks. I do need to compare and merge but I dont want to merge if a value was changed from its original value. Everything else would merge. Thanks though.
